/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #ACTIVITY_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ActivityBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Activity</code>
	 */
	String ACTIVITY_TYPE = "Activity";

	/**
	 * Part <code>activityId</code> of <code>Activity</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String ACTIVITY_ID_ATTR = "activityId";

	/**
	 * Part <code>costs</code> of <code>Activity</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Integer</code> in configuration.
	 * </p>
	 */
	String COSTS_ATTR = "costs";

	/**
	 * Part <code>description</code> of <code>Activity</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.wysiwyg:Html</code> in configuration.
	 * </p>
	 */
	String DESCRIPTION_ATTR = "description";

	/**
	 * Part <code>kind</code> of <code>Activity</code>
	 * 
	 * <p>
	 * Declared as <code>syn:ActivityKind</code> in configuration.
	 * </p>
	 */
	String KIND_ATTR = "kind";

	/**
	 * Part <code>name</code> of <code>Activity</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>valuations</code> of <code>Activity</code>
	 * 
	 * <p>
	 * Declared as <code>kpi:Valuation</code> in configuration.
	 * </p>
	 */
	String VALUATIONS_ATTR = "valuations";

	/**
	 * Getter for part {@link #ACTIVITY_ID_ATTR}.
	 */
	default String getActivityId() {
		return (String) tValueByName(ACTIVITY_ID_ATTR);
	}

	/**
	 * Setter for part {@link #ACTIVITY_ID_ATTR}.
	 */
	default void setActivityId(String newValue) {
		tUpdateByName(ACTIVITY_ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #COSTS_ATTR}.
	 */
	default Integer getCosts() {
		return (Integer) tValueByName(COSTS_ATTR);
	}

	/**
	 * Setter for part {@link #COSTS_ATTR}.
	 */
	default void setCosts(Integer newValue) {
		tUpdateByName(COSTS_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #DESCRIPTION_ATTR}.
	 */
	default com.top_logic.layout.wysiwyg.ui.StructuredText getDescription() {
		return (com.top_logic.layout.wysiwyg.ui.StructuredText) tValueByName(DESCRIPTION_ATTR);
	}

	/**
	 * Setter for part {@link #DESCRIPTION_ATTR}.
	 */
	default void setDescription(com.top_logic.layout.wysiwyg.ui.StructuredText newValue) {
		tUpdateByName(DESCRIPTION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #KIND_ATTR}.
	 */
	default com.top_logic.model.TLClassifier getKind() {
		return (com.top_logic.model.TLClassifier) tValueByName(KIND_ATTR);
	}

	/**
	 * Setter for part {@link #KIND_ATTR}.
	 */
	default void setKind(com.top_logic.model.TLClassifier newValue) {
		tUpdateByName(KIND_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #VALUATIONS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.model.TLObject> getValuations() {
		return (java.util.Set<? extends com.top_logic.model.TLObject>) tValueByName(VALUATIONS_ATTR);
	}

	/**
	 * Live view of the {@link #VALUATIONS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.model.TLObject> getValuationsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(VALUATIONS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.model.TLObject> result = (java.util.Set<com.top_logic.model.TLObject>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #VALUATIONS_ATTR}.
	 */
	default void setValuations(java.util.Set<com.top_logic.model.TLObject> newValue) {
		tUpdateByName(VALUATIONS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #VALUATIONS_ATTR} reference.
	 */
	default void addValuation(com.top_logic.model.TLObject newValue) {
		tAddByName(VALUATIONS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #VALUATIONS_ATTR} reference.
	 */
	default void removeValuation(com.top_logic.model.TLObject oldValue) {
		tRemoveByName(VALUATIONS_ATTR, oldValue);
	}

}
