/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #COMPONENT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ComponentBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Component</code>
	 */
	String COMPONENT_TYPE = "Component";

	/**
	 * Part <code>componentID</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String COMPONENT_ID_ATTR = "componentID";

	/**
	 * Part <code>name</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>price</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_ATTR = "price";

	/**
	 * Part <code>risks</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>risk:Risk</code> in configuration.
	 * </p>
	 */
	String RISKS_ATTR = "risks";

	/**
	 * Part <code>used</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>fma:Connection</code> in configuration.
	 * </p>
	 */
	String USED_ATTR = "used";

	/**
	 * Getter for part {@link #COMPONENT_ID_ATTR}.
	 */
	default String getComponentID() {
		return (String) tValueByName(COMPONENT_ID_ATTR);
	}

	/**
	 * Setter for part {@link #COMPONENT_ID_ATTR}.
	 */
	default void setComponentID(String newValue) {
		tUpdateByName(COMPONENT_ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PRICE_ATTR}.
	 */
	default Double getPrice() {
		return (Double) tValueByName(PRICE_ATTR);
	}

	/**
	 * Setter for part {@link #PRICE_ATTR}.
	 */
	default void setPrice(Double newValue) {
		tUpdateByName(PRICE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #RISKS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.risk.interfaces.Risk> getRisks() {
		return (java.util.Set<? extends com.top_logic.synchra.risk.interfaces.Risk>) tValueByName(RISKS_ATTR);
	}

	/**
	 * Getter for part {@link #USED_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.Connection> getUsed() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.Connection>) tValueByName(USED_ATTR);
	}

}
