/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #COMPONENT_NODE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ComponentNodeBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>ComponentNode</code>
	 */
	String COMPONENT_NODE_TYPE = "ComponentNode";

	/**
	 * Part <code>children</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>syn:ComponentNode</code> in configuration.
	 * </p>
	 */
	String CHILDREN_ATTR = "children";

	/**
	 * Part <code>component</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>syn:Component</code> in configuration.
	 * </p>
	 */
	String COMPONENT_ATTR = "component";

	/**
	 * Part <code>connection</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>syn:Connection</code> in configuration.
	 * </p>
	 */
	String CONNECTION_ATTR = "connection";

	/**
	 * Part <code>goalPrice</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Float</code> in configuration.
	 * </p>
	 */
	String GOAL_PRICE_ATTR = "goalPrice";

	/**
	 * Part <code>name</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>parent</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>syn:ComponentNode</code> in configuration.
	 * </p>
	 */
	String PARENT_ATTR = "parent";

	/**
	 * Part <code>price</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_ATTR = "price";

	/**
	 * Part <code>priceActivityContribution</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_ACTIVITY_CONTRIBUTION_ATTR = "priceActivityContribution";

	/**
	 * Part <code>priceActivityPrognose</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_ACTIVITY_PROGNOSE_ATTR = "priceActivityPrognose";

	/**
	 * Part <code>priceAfterActivities</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_AFTER_ACTIVITIES_ATTR = "priceAfterActivities";

	/**
	 * Part <code>product</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>syn:Product</code> in configuration.
	 * </p>
	 */
	String PRODUCT_ATTR = "product";

	/**
	 * Part <code>prognose</code> of <code>ComponentNode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PROGNOSE_ATTR = "prognose";

	/**
	 * Getter for part {@link #CHILDREN_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.ComponentNode> getChildren() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.ComponentNode>) tValueByName(CHILDREN_ATTR);
	}

	/**
	 * Getter for part {@link #COMPONENT_ATTR}.
	 */
	default com.top_logic.synchra.model.interfaces.Component getComponent() {
		return (com.top_logic.synchra.model.interfaces.Component) tValueByName(COMPONENT_ATTR);
	}

	/**
	 * Setter for part {@link #COMPONENT_ATTR}.
	 */
	default void setComponent(com.top_logic.synchra.model.interfaces.Component newValue) {
		tUpdateByName(COMPONENT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #CONNECTION_ATTR}.
	 */
	default com.top_logic.synchra.model.interfaces.Connection getConnection() {
		return (com.top_logic.synchra.model.interfaces.Connection) tValueByName(CONNECTION_ATTR);
	}

	/**
	 * Setter for part {@link #CONNECTION_ATTR}.
	 */
	default void setConnection(com.top_logic.synchra.model.interfaces.Connection newValue) {
		tUpdateByName(CONNECTION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #GOAL_PRICE_ATTR}.
	 */
	default Float getGoalPrice() {
		return (Float) tValueByName(GOAL_PRICE_ATTR);
	}

	/**
	 * Getter for part {@link #PARENT_ATTR}.
	 */
	default com.top_logic.synchra.model.interfaces.ComponentNode getParent() {
		return (com.top_logic.synchra.model.interfaces.ComponentNode) tValueByName(PARENT_ATTR);
	}

	/**
	 * Setter for part {@link #PARENT_ATTR}.
	 */
	default void setParent(com.top_logic.synchra.model.interfaces.ComponentNode newValue) {
		tUpdateByName(PARENT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PRICE_ATTR}.
	 */
	default Double getPrice() {
		return (Double) tValueByName(PRICE_ATTR);
	}

	/**
	 * Getter for part {@link #PRICE_ACTIVITY_CONTRIBUTION_ATTR}.
	 */
	default Double getPriceActivityContribution() {
		return (Double) tValueByName(PRICE_ACTIVITY_CONTRIBUTION_ATTR);
	}

	/**
	 * Getter for part {@link #PRICE_ACTIVITY_PROGNOSE_ATTR}.
	 */
	default Double getPriceActivityPrognose() {
		return (Double) tValueByName(PRICE_ACTIVITY_PROGNOSE_ATTR);
	}

	/**
	 * Getter for part {@link #PRICE_AFTER_ACTIVITIES_ATTR}.
	 */
	default Double getPriceAfterActivities() {
		return (Double) tValueByName(PRICE_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Getter for part {@link #PRODUCT_ATTR}.
	 */
	default com.top_logic.synchra.model.interfaces.Product getProduct() {
		return (com.top_logic.synchra.model.interfaces.Product) tValueByName(PRODUCT_ATTR);
	}

	/**
	 * Setter for part {@link #PRODUCT_ATTR}.
	 */
	default void setProduct(com.top_logic.synchra.model.interfaces.Product newValue) {
		tUpdateByName(PRODUCT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PROGNOSE_ATTR}.
	 */
	default Double getPrognose() {
		return (Double) tValueByName(PROGNOSE_ATTR);
	}

}
