/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #COMPONENT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ComponentBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Component</code>
	 */
	String COMPONENT_TYPE = "Component";

	/**
	 * Part <code>componentID</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String COMPONENT_ID_ATTR = "componentID";

	/**
	 * Part <code>name</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>pictures</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.imagegallery:GalleryImage</code> in configuration.
	 * </p>
	 */
	String PICTURES_ATTR = "pictures";

	/**
	 * Part <code>price</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_ATTR = "price";

	/**
	 * Part <code>priceActivityContribution</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_ACTIVITY_CONTRIBUTION_ATTR = "priceActivityContribution";

	/**
	 * Part <code>priceAfterActivities</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String PRICE_AFTER_ACTIVITIES_ATTR = "priceAfterActivities";

	/**
	 * Part <code>risks</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>risk:Risk</code> in configuration.
	 * </p>
	 */
	String RISKS_ATTR = "risks";

	/**
	 * Part <code>used</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>syn:Connection</code> in configuration.
	 * </p>
	 */
	String USED_ATTR = "used";

	/**
	 * Part <code>weight</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String WEIGHT_ATTR = "weight";

	/**
	 * Part <code>weightActivityContribution</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String WEIGHT_ACTIVITY_CONTRIBUTION_ATTR = "weightActivityContribution";

	/**
	 * Part <code>weightAfterActivities</code> of <code>Component</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String WEIGHT_AFTER_ACTIVITIES_ATTR = "weightAfterActivities";

	/**
	 * Getter for part {@link #COMPONENT_ID_ATTR}.
	 */
	default String getComponentID() {
		return (String) tValueByName(COMPONENT_ID_ATTR);
	}

	/**
	 * Setter for part {@link #COMPONENT_ID_ATTR}.
	 */
	default void setComponentID(String newValue) {
		tUpdateByName(COMPONENT_ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PICTURES_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.element.model.imagegallery.GalleryImage> getPictures() {
		return (java.util.List<? extends com.top_logic.element.model.imagegallery.GalleryImage>) tValueByName(PICTURES_ATTR);
	}

	/**
	 * Setter for part {@link #PICTURES_ATTR}.
	 */
	default void setPictures(java.util.List<com.top_logic.element.model.imagegallery.GalleryImage> newValue) {
		tUpdateByName(PICTURES_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #PICTURES_ATTR} reference.
	 */
	default void addPicture(com.top_logic.element.model.imagegallery.GalleryImage newValue) {
		tAddByName(PICTURES_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #PICTURES_ATTR} reference.
	 */
	default void removePicture(com.top_logic.element.model.imagegallery.GalleryImage oldValue) {
		tRemoveByName(PICTURES_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #PRICE_ATTR}.
	 */
	default Double getPrice() {
		return (Double) tValueByName(PRICE_ATTR);
	}

	/**
	 * Setter for part {@link #PRICE_ATTR}.
	 */
	default void setPrice(Double newValue) {
		tUpdateByName(PRICE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PRICE_ACTIVITY_CONTRIBUTION_ATTR}.
	 */
	default Double getPriceActivityContribution() {
		return (Double) tValueByName(PRICE_ACTIVITY_CONTRIBUTION_ATTR);
	}

	/**
	 * Getter for part {@link #PRICE_AFTER_ACTIVITIES_ATTR}.
	 */
	default Double getPriceAfterActivities() {
		return (Double) tValueByName(PRICE_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Getter for part {@link #RISKS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.risk.interfaces.Risk> getRisks() {
		return (java.util.Set<? extends com.top_logic.synchra.risk.interfaces.Risk>) tValueByName(RISKS_ATTR);
	}

	/**
	 * Getter for part {@link #USED_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.Connection> getUsed() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.Connection>) tValueByName(USED_ATTR);
	}

	/**
	 * Getter for part {@link #WEIGHT_ATTR}.
	 */
	default Double getWeight() {
		return (Double) tValueByName(WEIGHT_ATTR);
	}

	/**
	 * Setter for part {@link #WEIGHT_ATTR}.
	 */
	default void setWeight(Double newValue) {
		tUpdateByName(WEIGHT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #WEIGHT_ACTIVITY_CONTRIBUTION_ATTR}.
	 */
	default Double getWeightActivityContribution() {
		return (Double) tValueByName(WEIGHT_ACTIVITY_CONTRIBUTION_ATTR);
	}

	/**
	 * Getter for part {@link #WEIGHT_AFTER_ACTIVITIES_ATTR}.
	 */
	default Double getWeightAfterActivities() {
		return (Double) tValueByName(WEIGHT_AFTER_ACTIVITIES_ATTR);
	}

}
