/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #CONSTRUCTION_GROUP_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ConstructionGroupBase extends com.top_logic.synchra.model.interfaces.Component {

	/**
	 * Name of type <code>ConstructionGroup</code>
	 */
	String CONSTRUCTION_GROUP_TYPE = "ConstructionGroup";

	/**
	 * Part <code>consistsOf</code> of <code>ConstructionGroup</code>
	 * 
	 * <p>
	 * Declared as <code>fma:Connection</code> in configuration.
	 * </p>
	 */
	String CONSISTS_OF_ATTR = "consistsOf";

	/**
	 * Part <code>constructionGroupId</code> of <code>ConstructionGroup</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String CONSTRUCTION_GROUP_ID_ATTR = "constructionGroupId";

	/**
	 * Getter for part {@link #CONSISTS_OF_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.Connection> getConsistsOf() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.Connection>) tValueByName(CONSISTS_OF_ATTR);
	}

	/**
	 * Live view of the {@link #CONSISTS_OF_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.synchra.model.interfaces.Connection> getConsistsOfModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(CONSISTS_OF_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.synchra.model.interfaces.Connection> result = (java.util.Set<com.top_logic.synchra.model.interfaces.Connection>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #CONSISTS_OF_ATTR}.
	 */
	default void setConsistsOf(java.util.Set<com.top_logic.synchra.model.interfaces.Connection> newValue) {
		tUpdateByName(CONSISTS_OF_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #CONSISTS_OF_ATTR} reference.
	 */
	default void addConsistsOf(com.top_logic.synchra.model.interfaces.Connection newValue) {
		tAddByName(CONSISTS_OF_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #CONSISTS_OF_ATTR} reference.
	 */
	default void removeConsistsOf(com.top_logic.synchra.model.interfaces.Connection oldValue) {
		tRemoveByName(CONSISTS_OF_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #CONSTRUCTION_GROUP_ID_ATTR}.
	 */
	default String getConstructionGroupId() {
		return (String) tValueByName(CONSTRUCTION_GROUP_ID_ATTR);
	}

	/**
	 * Setter for part {@link #CONSTRUCTION_GROUP_ID_ATTR}.
	 */
	default void setConstructionGroupId(String newValue) {
		tUpdateByName(CONSTRUCTION_GROUP_ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PRICE_ATTR}.
	 */
	@Override
	default Double getPrice() {
		return (Double) tValueByName(PRICE_ATTR);
	}

}
