/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #PART_CATALOG_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface PartCatalogBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>PartCatalog</code>
	 */
	String PART_CATALOG_TYPE = "PartCatalog";

	/**
	 * Part <code>materialCompany</code> of <code>PartCatalog</code>
	 * 
	 * <p>
	 * Declared as <code>fma:PartsGroup</code> in configuration.
	 * </p>
	 */
	String MATERIAL_COMPANY_ATTR = "materialCompany";

	/**
	 * Part <code>materialGroups</code> of <code>PartCatalog</code>
	 * 
	 * <p>
	 * Declared as <code>fma:PartsGroup</code> in configuration.
	 * </p>
	 */
	String MATERIAL_GROUPS_ATTR = "materialGroups";

	/**
	 * Part <code>name</code> of <code>PartCatalog</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>partGroups</code> of <code>PartCatalog</code>
	 * 
	 * <p>
	 * Declared as <code>fma:PartsGroup</code> in configuration.
	 * </p>
	 */
	String PART_GROUPS_ATTR = "partGroups";

	/**
	 * Part <code>parts</code> of <code>PartCatalog</code>
	 * 
	 * <p>
	 * Declared as <code>fma:SinglePart</code> in configuration.
	 * </p>
	 */
	String PARTS_ATTR = "parts";

	/**
	 * Getter for part {@link #MATERIAL_COMPANY_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.PartsGroup> getMaterialCompany() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.PartsGroup>) tValueByName(MATERIAL_COMPANY_ATTR);
	}

	/**
	 * Getter for part {@link #MATERIAL_GROUPS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.PartsGroup> getMaterialGroups() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.PartsGroup>) tValueByName(MATERIAL_GROUPS_ATTR);
	}

	/**
	 * Getter for part {@link #PART_GROUPS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.PartsGroup> getPartGroups() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.PartsGroup>) tValueByName(PART_GROUPS_ATTR);
	}

	/**
	 * Getter for part {@link #PARTS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.SinglePart> getParts() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.SinglePart>) tValueByName(PARTS_ATTR);
	}

	/**
	 * Live view of the {@link #PARTS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.synchra.model.interfaces.SinglePart> getPartsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(PARTS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.synchra.model.interfaces.SinglePart> result = (java.util.Set<com.top_logic.synchra.model.interfaces.SinglePart>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #PARTS_ATTR}.
	 */
	default void setParts(java.util.Set<com.top_logic.synchra.model.interfaces.SinglePart> newValue) {
		tUpdateByName(PARTS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #PARTS_ATTR} reference.
	 */
	default void addPart(com.top_logic.synchra.model.interfaces.SinglePart newValue) {
		tAddByName(PARTS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #PARTS_ATTR} reference.
	 */
	default void removePart(com.top_logic.synchra.model.interfaces.SinglePart oldValue) {
		tRemoveByName(PARTS_ATTR, oldValue);
	}

}
