/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #PARTS_GROUP_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface PartsGroupBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>PartsGroup</code>
	 */
	String PARTS_GROUP_TYPE = "PartsGroup";

	/**
	 * Part <code>name</code> of <code>PartsGroup</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>parts</code> of <code>PartsGroup</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model:TLObject</code> in configuration.
	 * </p>
	 */
	String PARTS_ATTR = "parts";

	/**
	 * Getter for part {@link #PARTS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.model.TLObject> getParts() {
		return (java.util.Set<? extends com.top_logic.model.TLObject>) tValueByName(PARTS_ATTR);
	}

	/**
	 * Live view of the {@link #PARTS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.model.TLObject> getPartsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(PARTS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.model.TLObject> result = (java.util.Set<com.top_logic.model.TLObject>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #PARTS_ATTR}.
	 */
	default void setParts(java.util.Set<com.top_logic.model.TLObject> newValue) {
		tUpdateByName(PARTS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #PARTS_ATTR} reference.
	 */
	default void addPart(com.top_logic.model.TLObject newValue) {
		tAddByName(PARTS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #PARTS_ATTR} reference.
	 */
	default void removePart(com.top_logic.model.TLObject oldValue) {
		tRemoveByName(PARTS_ATTR, oldValue);
	}

}
