/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #PROBLEM_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ProblemBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Problem</code>
	 */
	String PROBLEM_TYPE = "Problem";

	/**
	 * Part <code>components</code> of <code>Problem</code>
	 * 
	 * <p>
	 * Declared as <code>syn:Component</code> in configuration.
	 * </p>
	 */
	String COMPONENTS_ATTR = "components";

	/**
	 * Part <code>description</code> of <code>Problem</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.wysiwyg:Html</code> in configuration.
	 * </p>
	 */
	String DESCRIPTION_ATTR = "description";

	/**
	 * Part <code>name</code> of <code>Problem</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>solvingActivities</code> of <code>Problem</code>
	 * 
	 * <p>
	 * Declared as <code>syn:Activity</code> in configuration.
	 * </p>
	 */
	String SOLVING_ACTIVITIES_ATTR = "solvingActivities";

	/**
	 * Getter for part {@link #COMPONENTS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.Component> getComponents() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.Component>) tValueByName(COMPONENTS_ATTR);
	}

	/**
	 * Live view of the {@link #COMPONENTS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.synchra.model.interfaces.Component> getComponentsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(COMPONENTS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.synchra.model.interfaces.Component> result = (java.util.Set<com.top_logic.synchra.model.interfaces.Component>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #COMPONENTS_ATTR}.
	 */
	default void setComponents(java.util.Set<com.top_logic.synchra.model.interfaces.Component> newValue) {
		tUpdateByName(COMPONENTS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #COMPONENTS_ATTR} reference.
	 */
	default void addComponent(com.top_logic.synchra.model.interfaces.Component newValue) {
		tAddByName(COMPONENTS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #COMPONENTS_ATTR} reference.
	 */
	default void removeComponent(com.top_logic.synchra.model.interfaces.Component oldValue) {
		tRemoveByName(COMPONENTS_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #DESCRIPTION_ATTR}.
	 */
	default com.top_logic.layout.wysiwyg.ui.StructuredText getDescription() {
		return (com.top_logic.layout.wysiwyg.ui.StructuredText) tValueByName(DESCRIPTION_ATTR);
	}

	/**
	 * Setter for part {@link #DESCRIPTION_ATTR}.
	 */
	default void setDescription(com.top_logic.layout.wysiwyg.ui.StructuredText newValue) {
		tUpdateByName(DESCRIPTION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #SOLVING_ACTIVITIES_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.Activity> getSolvingActivities() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.Activity>) tValueByName(SOLVING_ACTIVITIES_ATTR);
	}

	/**
	 * Live view of the {@link #SOLVING_ACTIVITIES_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.synchra.model.interfaces.Activity> getSolvingActivitiesModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(SOLVING_ACTIVITIES_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.synchra.model.interfaces.Activity> result = (java.util.Set<com.top_logic.synchra.model.interfaces.Activity>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #SOLVING_ACTIVITIES_ATTR}.
	 */
	default void setSolvingActivities(java.util.Set<com.top_logic.synchra.model.interfaces.Activity> newValue) {
		tUpdateByName(SOLVING_ACTIVITIES_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #SOLVING_ACTIVITIES_ATTR} reference.
	 */
	default void addSolvingActivity(com.top_logic.synchra.model.interfaces.Activity newValue) {
		tAddByName(SOLVING_ACTIVITIES_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #SOLVING_ACTIVITIES_ATTR} reference.
	 */
	default void removeSolvingActivity(com.top_logic.synchra.model.interfaces.Activity oldValue) {
		tRemoveByName(SOLVING_ACTIVITIES_ATTR, oldValue);
	}

}
