/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #PRODUCT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ProductBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Product</code>
	 */
	String PRODUCT_TYPE = "Product";

	/**
	 * Part <code>buildGroup</code> of <code>Product</code>
	 * 
	 * <p>
	 * Declared as <code>fma:ConstructionGroup</code> in configuration.
	 * </p>
	 */
	String BUILD_GROUP_ATTR = "buildGroup";

	/**
	 * Part <code>name</code> of <code>Product</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Getter for part {@link #BUILD_GROUP_ATTR}.
	 */
	default com.top_logic.synchra.model.interfaces.ConstructionGroup getBuildGroup() {
		return (com.top_logic.synchra.model.interfaces.ConstructionGroup) tValueByName(BUILD_GROUP_ATTR);
	}

	/**
	 * Setter for part {@link #BUILD_GROUP_ATTR}.
	 */
	default void setBuildGroup(com.top_logic.synchra.model.interfaces.ConstructionGroup newValue) {
		tUpdateByName(BUILD_GROUP_ATTR, newValue);
	}

}
