/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #SINGLE_PART_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface SinglePartBase extends com.top_logic.synchra.model.interfaces.Component {

	/**
	 * Name of type <code>SinglePart</code>
	 */
	String SINGLE_PART_TYPE = "SinglePart";

	/**
	 * Part <code>company</code> of <code>SinglePart</code>
	 * 
	 * <p>
	 * Declared as <code>fma:Company</code> in configuration.
	 * </p>
	 */
	String COMPANY_ATTR = "company";

	/**
	 * Part <code>material</code> of <code>SinglePart</code>
	 * 
	 * <p>
	 * Declared as <code>fma:Material</code> in configuration.
	 * </p>
	 */
	String MATERIAL_ATTR = "material";

	/**
	 * Getter for part {@link #COMPANY_ATTR}.
	 */
	default com.top_logic.synchra.model.interfaces.Company getCompany() {
		return (com.top_logic.synchra.model.interfaces.Company) tValueByName(COMPANY_ATTR);
	}

	/**
	 * Setter for part {@link #COMPANY_ATTR}.
	 */
	default void setCompany(com.top_logic.synchra.model.interfaces.Company newValue) {
		tUpdateByName(COMPANY_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #MATERIAL_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.synchra.model.interfaces.Material> getMaterial() {
		return (java.util.Set<? extends com.top_logic.synchra.model.interfaces.Material>) tValueByName(MATERIAL_ATTR);
	}

	/**
	 * Live view of the {@link #MATERIAL_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.synchra.model.interfaces.Material> getMaterialModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(MATERIAL_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.synchra.model.interfaces.Material> result = (java.util.Set<com.top_logic.synchra.model.interfaces.Material>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #MATERIAL_ATTR}.
	 */
	default void setMaterial(java.util.Set<com.top_logic.synchra.model.interfaces.Material> newValue) {
		tUpdateByName(MATERIAL_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #MATERIAL_ATTR} reference.
	 */
	default void addMaterial(com.top_logic.synchra.model.interfaces.Material newValue) {
		tAddByName(MATERIAL_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #MATERIAL_ATTR} reference.
	 */
	default void removeMaterial(com.top_logic.synchra.model.interfaces.Material oldValue) {
		tRemoveByName(MATERIAL_ATTR, oldValue);
	}

}
