/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model.implementation;

/**
 * Basic interface for {@link #TREE_ROOT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface TreeRootBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>TreeRoot</code>
	 */
	String TREE_ROOT_TYPE = "TreeRoot";

}
