/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.model;

/**
 * Factory for <code>syn</code> objects.
 * 
 * <p>
 * Note: this is generated code. Do not modify. Instead, create a subclass and register this in the module system.
 * </p>
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.FactoryGenerator}
 */
public class ModelFactory extends com.top_logic.element.meta.kbbased.AbstractElementFactory {

	/**
	 * Name of the structure <code>syn</code> defined by {@link ModelFactory}.
	 */
	public static final String SYN_STRUCTURE = "syn";

	/**
	 * Name of the enumeration <code>ActivityKind</code> in module {@value #SYN_STRUCTURE}.
	 */
	public static final String ACTIVITY_KIND_ENUM = "ActivityKind";

	/**
	 * Name of the classifier <code>ORGANISATORIC</code> in enumeration {@value #ACTIVITY_KIND_ENUM}.
	 */
	public static final String ORGANISATORIC_ACTIVITY_KIND_CLASSIFIER = "ORGANISATORIC";

	/**
	 * Name of the classifier <code>TECHNICAL</code> in enumeration {@value #ACTIVITY_KIND_ENUM}.
	 */
	public static final String TECHNICAL_ACTIVITY_KIND_CLASSIFIER = "TECHNICAL";

	/**
	 * Name of the enumeration <code>CompanyStructure</code> in module {@value #SYN_STRUCTURE}.
	 */
	public static final String COMPANY_STRUCTURE_ENUM = "CompanyStructure";

	/**
	 * Name of the classifier <code>AG</code> in enumeration {@value #COMPANY_STRUCTURE_ENUM}.
	 */
	public static final String AG_COMPANY_STRUCTURE_CLASSIFIER = "AG";

	/**
	 * Name of the classifier <code>CoKG</code> in enumeration {@value #COMPANY_STRUCTURE_ENUM}.
	 */
	public static final String CO_KG_COMPANY_STRUCTURE_CLASSIFIER = "CoKG";

	/**
	 * Name of the classifier <code>GmbH</code> in enumeration {@value #COMPANY_STRUCTURE_ENUM}.
	 */
	public static final String GMB_H_COMPANY_STRUCTURE_CLASSIFIER = "GmbH";

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity} type.
	 */
	public static com.top_logic.model.TLClass getActivityType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Activity.ACTIVITY_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity#ACTIVITY_ID_ATTR} of {@link com.top_logic.synchra.model.interfaces.Activity}.
	 */
	public static com.top_logic.model.TLProperty getActivityIdActivityAttr() {
		return (com.top_logic.model.TLProperty) getActivityType().getPart(com.top_logic.synchra.model.interfaces.Activity.ACTIVITY_ID_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity#COSTS_ATTR} of {@link com.top_logic.synchra.model.interfaces.Activity}.
	 */
	public static com.top_logic.model.TLProperty getCostsActivityAttr() {
		return (com.top_logic.model.TLProperty) getActivityType().getPart(com.top_logic.synchra.model.interfaces.Activity.COSTS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity#DESCRIPTION_ATTR} of {@link com.top_logic.synchra.model.interfaces.Activity}.
	 */
	public static com.top_logic.model.TLProperty getDescriptionActivityAttr() {
		return (com.top_logic.model.TLProperty) getActivityType().getPart(com.top_logic.synchra.model.interfaces.Activity.DESCRIPTION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity#KIND_ATTR} of {@link com.top_logic.synchra.model.interfaces.Activity}.
	 */
	public static com.top_logic.model.TLReference getKindActivityAttr() {
		return (com.top_logic.model.TLReference) getActivityType().getPart(com.top_logic.synchra.model.interfaces.Activity.KIND_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.Activity}.
	 */
	public static com.top_logic.model.TLProperty getNameActivityAttr() {
		return (com.top_logic.model.TLProperty) getActivityType().getPart(com.top_logic.synchra.model.interfaces.Activity.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Activity#VALUATIONS_ATTR} of {@link com.top_logic.synchra.model.interfaces.Activity}.
	 */
	public static com.top_logic.model.TLReference getValuationsActivityAttr() {
		return (com.top_logic.model.TLReference) getActivityType().getPart(com.top_logic.synchra.model.interfaces.Activity.VALUATIONS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Company} type.
	 */
	public static com.top_logic.model.TLClass getCompanyType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Company.COMPANY_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Company#CONTACT_PERSON_ATTR} of {@link com.top_logic.synchra.model.interfaces.Company}.
	 */
	public static com.top_logic.model.TLProperty getContactPersonCompanyAttr() {
		return (com.top_logic.model.TLProperty) getCompanyType().getPart(com.top_logic.synchra.model.interfaces.Company.CONTACT_PERSON_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Company#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.Company}.
	 */
	public static com.top_logic.model.TLProperty getNameCompanyAttr() {
		return (com.top_logic.model.TLProperty) getCompanyType().getPart(com.top_logic.synchra.model.interfaces.Company.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Company#PHONE_ATTR} of {@link com.top_logic.synchra.model.interfaces.Company}.
	 */
	public static com.top_logic.model.TLProperty getPhoneCompanyAttr() {
		return (com.top_logic.model.TLProperty) getCompanyType().getPart(com.top_logic.synchra.model.interfaces.Company.PHONE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Company#STRUCTURE_ATTR} of {@link com.top_logic.synchra.model.interfaces.Company}.
	 */
	public static com.top_logic.model.TLReference getStructureCompanyAttr() {
		return (com.top_logic.model.TLReference) getCompanyType().getPart(com.top_logic.synchra.model.interfaces.Company.STRUCTURE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component} type.
	 */
	public static com.top_logic.model.TLClass getComponentType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Component.COMPONENT_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#COMPONENT_ID_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getComponentIDComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.COMPONENT_ID_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getNameComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#PICTURES_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLReference getPicturesComponentAttr() {
		return (com.top_logic.model.TLReference) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.PICTURES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#PRICE_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getPriceComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.PRICE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#PRICE_ACTIVITY_CONTRIBUTION_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getPriceActivityContributionComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.PRICE_ACTIVITY_CONTRIBUTION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#PRICE_AFTER_ACTIVITIES_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getPriceAfterActivitiesComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.PRICE_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#RISKS_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLReference getRisksComponentAttr() {
		return (com.top_logic.model.TLReference) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.RISKS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#USED_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLReference getUsedComponentAttr() {
		return (com.top_logic.model.TLReference) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.USED_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#WEIGHT_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getWeightComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.WEIGHT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#WEIGHT_ACTIVITY_CONTRIBUTION_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getWeightActivityContributionComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.WEIGHT_ACTIVITY_CONTRIBUTION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Component#WEIGHT_AFTER_ACTIVITIES_ATTR} of {@link com.top_logic.synchra.model.interfaces.Component}.
	 */
	public static com.top_logic.model.TLProperty getWeightAfterActivitiesComponentAttr() {
		return (com.top_logic.model.TLProperty) getComponentType().getPart(com.top_logic.synchra.model.interfaces.Component.WEIGHT_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup} type.
	 */
	public static com.top_logic.model.TLClass getConstructionGroupType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.ConstructionGroup.CONSTRUCTION_GROUP_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#COMPONENT_ID_ATTR} of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup}.
	 */
	public static com.top_logic.model.TLProperty getComponentIDConstructionGroupAttr() {
		return (com.top_logic.model.TLProperty) getConstructionGroupType().getPart(com.top_logic.synchra.model.interfaces.ConstructionGroup.COMPONENT_ID_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#CONSISTS_OF_ATTR} of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup}.
	 */
	public static com.top_logic.model.TLReference getConsistsOfConstructionGroupAttr() {
		return (com.top_logic.model.TLReference) getConstructionGroupType().getPart(com.top_logic.synchra.model.interfaces.ConstructionGroup.CONSISTS_OF_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#PRICE_ATTR} of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup}.
	 */
	public static com.top_logic.model.TLProperty getPriceConstructionGroupAttr() {
		return (com.top_logic.model.TLProperty) getConstructionGroupType().getPart(com.top_logic.synchra.model.interfaces.ConstructionGroup.PRICE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#PRICE_AFTER_ACTIVITIES_ATTR} of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup}.
	 */
	public static com.top_logic.model.TLProperty getPriceAfterActivitiesConstructionGroupAttr() {
		return (com.top_logic.model.TLProperty) getConstructionGroupType().getPart(com.top_logic.synchra.model.interfaces.ConstructionGroup.PRICE_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#WEIGHT_ATTR} of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup}.
	 */
	public static com.top_logic.model.TLProperty getWeightConstructionGroupAttr() {
		return (com.top_logic.model.TLProperty) getConstructionGroupType().getPart(com.top_logic.synchra.model.interfaces.ConstructionGroup.WEIGHT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#WEIGHT_AFTER_ACTIVITIES_ATTR} of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup}.
	 */
	public static com.top_logic.model.TLProperty getWeightAfterActivitiesConstructionGroupAttr() {
		return (com.top_logic.model.TLProperty) getConstructionGroupType().getPart(com.top_logic.synchra.model.interfaces.ConstructionGroup.WEIGHT_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.SinglePart} type.
	 */
	public static com.top_logic.model.TLClass getSinglePartType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.SinglePart.SINGLE_PART_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.SinglePart#CATALOG_ATTR} of {@link com.top_logic.synchra.model.interfaces.SinglePart}.
	 */
	public static com.top_logic.model.TLReference getCatalogSinglePartAttr() {
		return (com.top_logic.model.TLReference) getSinglePartType().getPart(com.top_logic.synchra.model.interfaces.SinglePart.CATALOG_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.SinglePart#COMPANY_ATTR} of {@link com.top_logic.synchra.model.interfaces.SinglePart}.
	 */
	public static com.top_logic.model.TLReference getCompanySinglePartAttr() {
		return (com.top_logic.model.TLReference) getSinglePartType().getPart(com.top_logic.synchra.model.interfaces.SinglePart.COMPANY_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.SinglePart#COMPONENT_ID_ATTR} of {@link com.top_logic.synchra.model.interfaces.SinglePart}.
	 */
	public static com.top_logic.model.TLProperty getComponentIDSinglePartAttr() {
		return (com.top_logic.model.TLProperty) getSinglePartType().getPart(com.top_logic.synchra.model.interfaces.SinglePart.COMPONENT_ID_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.SinglePart#MATERIAL_ATTR} of {@link com.top_logic.synchra.model.interfaces.SinglePart}.
	 */
	public static com.top_logic.model.TLReference getMaterialSinglePartAttr() {
		return (com.top_logic.model.TLReference) getSinglePartType().getPart(com.top_logic.synchra.model.interfaces.SinglePart.MATERIAL_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode} type.
	 */
	public static com.top_logic.model.TLClass getComponentNodeType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.ComponentNode.COMPONENT_NODE_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#CHILDREN_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLReference getChildrenComponentNodeAttr() {
		return (com.top_logic.model.TLReference) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#COMPONENT_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLReference getComponentComponentNodeAttr() {
		return (com.top_logic.model.TLReference) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.COMPONENT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#CONNECTION_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLReference getConnectionComponentNodeAttr() {
		return (com.top_logic.model.TLReference) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.CONNECTION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLProperty getNameComponentNodeAttr() {
		return (com.top_logic.model.TLProperty) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#PARENT_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLReference getParentComponentNodeAttr() {
		return (com.top_logic.model.TLReference) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.PARENT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#PRICE_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLProperty getPriceComponentNodeAttr() {
		return (com.top_logic.model.TLProperty) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.PRICE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#PRICE_ACTIVITY_CONTRIBUTION_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLProperty getPriceActivityContributionComponentNodeAttr() {
		return (com.top_logic.model.TLProperty) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.PRICE_ACTIVITY_CONTRIBUTION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#PRICE_AFTER_ACTIVITIES_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLProperty getPriceAfterActivitiesComponentNodeAttr() {
		return (com.top_logic.model.TLProperty) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.PRICE_AFTER_ACTIVITIES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ComponentNode#PRODUCT_ATTR} of {@link com.top_logic.synchra.model.interfaces.ComponentNode}.
	 */
	public static com.top_logic.model.TLReference getProductComponentNodeAttr() {
		return (com.top_logic.model.TLReference) getComponentNodeType().getPart(com.top_logic.synchra.model.interfaces.ComponentNode.PRODUCT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Connection} type.
	 */
	public static com.top_logic.model.TLClass getConnectionType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Connection.CONNECTION_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Connection#CONSISTS_OF_ATTR} of {@link com.top_logic.synchra.model.interfaces.Connection}.
	 */
	public static com.top_logic.model.TLReference getConsistsOfConnectionAttr() {
		return (com.top_logic.model.TLReference) getConnectionType().getPart(com.top_logic.synchra.model.interfaces.Connection.CONSISTS_OF_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Connection#POSITION_ATTR} of {@link com.top_logic.synchra.model.interfaces.Connection}.
	 */
	public static com.top_logic.model.TLProperty getPositionConnectionAttr() {
		return (com.top_logic.model.TLProperty) getConnectionType().getPart(com.top_logic.synchra.model.interfaces.Connection.POSITION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Connection#USED_ATTR} of {@link com.top_logic.synchra.model.interfaces.Connection}.
	 */
	public static com.top_logic.model.TLReference getUsedConnectionAttr() {
		return (com.top_logic.model.TLReference) getConnectionType().getPart(com.top_logic.synchra.model.interfaces.Connection.USED_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Material} type.
	 */
	public static com.top_logic.model.TLClass getMaterialType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Material.MATERIAL_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Material#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.Material}.
	 */
	public static com.top_logic.model.TLProperty getNameMaterialAttr() {
		return (com.top_logic.model.TLProperty) getMaterialType().getPart(com.top_logic.synchra.model.interfaces.Material.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartCatalog} type.
	 */
	public static com.top_logic.model.TLClass getPartCatalogType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.PartCatalog.PART_CATALOG_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartCatalog#MATERIAL_COMPANY_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartCatalog}.
	 */
	public static com.top_logic.model.TLReference getMaterialCompanyPartCatalogAttr() {
		return (com.top_logic.model.TLReference) getPartCatalogType().getPart(com.top_logic.synchra.model.interfaces.PartCatalog.MATERIAL_COMPANY_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartCatalog#MATERIAL_GROUPS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartCatalog}.
	 */
	public static com.top_logic.model.TLReference getMaterialGroupsPartCatalogAttr() {
		return (com.top_logic.model.TLReference) getPartCatalogType().getPart(com.top_logic.synchra.model.interfaces.PartCatalog.MATERIAL_GROUPS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartCatalog#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartCatalog}.
	 */
	public static com.top_logic.model.TLProperty getNamePartCatalogAttr() {
		return (com.top_logic.model.TLProperty) getPartCatalogType().getPart(com.top_logic.synchra.model.interfaces.PartCatalog.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartCatalog#PART_GROUPS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartCatalog}.
	 */
	public static com.top_logic.model.TLReference getPartGroupsPartCatalogAttr() {
		return (com.top_logic.model.TLReference) getPartCatalogType().getPart(com.top_logic.synchra.model.interfaces.PartCatalog.PART_GROUPS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartCatalog#PARTS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartCatalog}.
	 */
	public static com.top_logic.model.TLReference getPartsPartCatalogAttr() {
		return (com.top_logic.model.TLReference) getPartCatalogType().getPart(com.top_logic.synchra.model.interfaces.PartCatalog.PARTS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsGroup} type.
	 */
	public static com.top_logic.model.TLClass getPartsGroupType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.PartsGroup.PARTS_GROUP_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsGroup#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsGroup}.
	 */
	public static com.top_logic.model.TLProperty getNamePartsGroupAttr() {
		return (com.top_logic.model.TLProperty) getPartsGroupType().getPart(com.top_logic.synchra.model.interfaces.PartsGroup.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsGroup#PARTS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsGroup}.
	 */
	public static com.top_logic.model.TLReference getPartsPartsGroupAttr() {
		return (com.top_logic.model.TLReference) getPartsGroupType().getPart(com.top_logic.synchra.model.interfaces.PartsGroup.PARTS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry} type.
	 */
	public static com.top_logic.model.TLClass getPartsListEntryType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.PartsListEntry.PARTS_LIST_ENTRY_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#CONNECTIONS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLReference getConnectionsPartsListEntryAttr() {
		return (com.top_logic.model.TLReference) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.CONNECTIONS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#COSTS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLProperty getCostsPartsListEntryAttr() {
		return (com.top_logic.model.TLProperty) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.COSTS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#COUNT_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLProperty getCountPartsListEntryAttr() {
		return (com.top_logic.model.TLProperty) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.COUNT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#MATERIALS_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLReference getMaterialsPartsListEntryAttr() {
		return (com.top_logic.model.TLReference) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.MATERIALS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#PART_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLReference getPartPartsListEntryAttr() {
		return (com.top_logic.model.TLReference) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.PART_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#PRODUCER_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLReference getProducerPartsListEntryAttr() {
		return (com.top_logic.model.TLReference) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.PRODUCER_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.PartsListEntry#SINGLE_PRICE_ATTR} of {@link com.top_logic.synchra.model.interfaces.PartsListEntry}.
	 */
	public static com.top_logic.model.TLProperty getSinglePricePartsListEntryAttr() {
		return (com.top_logic.model.TLProperty) getPartsListEntryType().getPart(com.top_logic.synchra.model.interfaces.PartsListEntry.SINGLE_PRICE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Problem} type.
	 */
	public static com.top_logic.model.TLClass getProblemType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Problem.PROBLEM_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Problem#COMPONENTS_ATTR} of {@link com.top_logic.synchra.model.interfaces.Problem}.
	 */
	public static com.top_logic.model.TLReference getComponentsProblemAttr() {
		return (com.top_logic.model.TLReference) getProblemType().getPart(com.top_logic.synchra.model.interfaces.Problem.COMPONENTS_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Problem#DESCRIPTION_ATTR} of {@link com.top_logic.synchra.model.interfaces.Problem}.
	 */
	public static com.top_logic.model.TLProperty getDescriptionProblemAttr() {
		return (com.top_logic.model.TLProperty) getProblemType().getPart(com.top_logic.synchra.model.interfaces.Problem.DESCRIPTION_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Problem#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.Problem}.
	 */
	public static com.top_logic.model.TLProperty getNameProblemAttr() {
		return (com.top_logic.model.TLProperty) getProblemType().getPart(com.top_logic.synchra.model.interfaces.Problem.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Problem#SOLVING_ACTIVITIES_ATTR} of {@link com.top_logic.synchra.model.interfaces.Problem}.
	 */
	public static com.top_logic.model.TLReference getSolvingActivitiesProblemAttr() {
		return (com.top_logic.model.TLReference) getProblemType().getPart(com.top_logic.synchra.model.interfaces.Problem.SOLVING_ACTIVITIES_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Product} type.
	 */
	public static com.top_logic.model.TLClass getProductType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.Product.PRODUCT_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Product#BUILD_GROUP_ATTR} of {@link com.top_logic.synchra.model.interfaces.Product}.
	 */
	public static com.top_logic.model.TLReference getBuildGroupProductAttr() {
		return (com.top_logic.model.TLReference) getProductType().getPart(com.top_logic.synchra.model.interfaces.Product.BUILD_GROUP_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Product#NAME_ATTR} of {@link com.top_logic.synchra.model.interfaces.Product}.
	 */
	public static com.top_logic.model.TLProperty getNameProductAttr() {
		return (com.top_logic.model.TLProperty) getProductType().getPart(com.top_logic.synchra.model.interfaces.Product.NAME_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.Product#PRODUCT_ID_ATTR} of {@link com.top_logic.synchra.model.interfaces.Product}.
	 */
	public static com.top_logic.model.TLProperty getProductIdProductAttr() {
		return (com.top_logic.model.TLProperty) getProductType().getPart(com.top_logic.synchra.model.interfaces.Product.PRODUCT_ID_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ProductSelection} type.
	 */
	public static com.top_logic.model.TLClass getProductSelectionType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(com.top_logic.synchra.model.interfaces.ProductSelection.PRODUCT_SELECTION_TYPE);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ProductSelection#PRODUCT_ATTR} of {@link com.top_logic.synchra.model.interfaces.ProductSelection}.
	 */
	public static com.top_logic.model.TLReference getProductProductSelectionAttr() {
		return (com.top_logic.model.TLReference) getProductSelectionType().getPart(com.top_logic.synchra.model.interfaces.ProductSelection.PRODUCT_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ProductSelection#REFERENCE_DATE_ATTR} of {@link com.top_logic.synchra.model.interfaces.ProductSelection}.
	 */
	public static com.top_logic.model.TLProperty getReferenceDateProductSelectionAttr() {
		return (com.top_logic.model.TLProperty) getProductSelectionType().getPart(com.top_logic.synchra.model.interfaces.ProductSelection.REFERENCE_DATE_ATTR);
	}

	/**
	 * Lookup {@link com.top_logic.synchra.model.interfaces.ProductSelection#RULE_ATTR} of {@link com.top_logic.synchra.model.interfaces.ProductSelection}.
	 */
	public static com.top_logic.model.TLProperty getRuleProductSelectionAttr() {
		return (com.top_logic.model.TLProperty) getProductSelectionType().getPart(com.top_logic.synchra.model.interfaces.ProductSelection.RULE_ATTR);
	}

	/**
	 * Lookup {@value #ACTIVITY_KIND_ENUM} enumeration.
	 */
	public static com.top_logic.model.TLEnumeration getActivityKindEnum() {
		return (com.top_logic.model.TLEnumeration) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(ACTIVITY_KIND_ENUM);
	}

	/**
	 * Lookup classifier {@value #ORGANISATORIC_ACTIVITY_KIND_CLASSIFIER} of enumeration {@value #ACTIVITY_KIND_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getORGANISATORICActivityKindClassifier() {
		return getActivityKindEnum().getClassifier(ORGANISATORIC_ACTIVITY_KIND_CLASSIFIER);
	}

	/**
	 * Lookup classifier {@value #TECHNICAL_ACTIVITY_KIND_CLASSIFIER} of enumeration {@value #ACTIVITY_KIND_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getTECHNICALActivityKindClassifier() {
		return getActivityKindEnum().getClassifier(TECHNICAL_ACTIVITY_KIND_CLASSIFIER);
	}

	/**
	 * Lookup {@value #COMPANY_STRUCTURE_ENUM} enumeration.
	 */
	public static com.top_logic.model.TLEnumeration getCompanyStructureEnum() {
		return (com.top_logic.model.TLEnumeration) com.top_logic.util.model.ModelService.getApplicationModel().getModule(SYN_STRUCTURE).getType(COMPANY_STRUCTURE_ENUM);
	}

	/**
	 * Lookup classifier {@value #AG_COMPANY_STRUCTURE_CLASSIFIER} of enumeration {@value #COMPANY_STRUCTURE_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getAGCompanyStructureClassifier() {
		return getCompanyStructureEnum().getClassifier(AG_COMPANY_STRUCTURE_CLASSIFIER);
	}

	/**
	 * Lookup classifier {@value #CO_KG_COMPANY_STRUCTURE_CLASSIFIER} of enumeration {@value #COMPANY_STRUCTURE_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getCoKGCompanyStructureClassifier() {
		return getCompanyStructureEnum().getClassifier(CO_KG_COMPANY_STRUCTURE_CLASSIFIER);
	}

	/**
	 * Lookup classifier {@value #GMB_H_COMPANY_STRUCTURE_CLASSIFIER} of enumeration {@value #COMPANY_STRUCTURE_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getGmbHCompanyStructureClassifier() {
		return getCompanyStructureEnum().getClassifier(GMB_H_COMPANY_STRUCTURE_CLASSIFIER);
	}

	/**
	 * Name of type <code>Activity</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Activity#ACTIVITY_TYPE}.
	 */
	@Deprecated
	public static final String ACTIVITY_NODE = com.top_logic.synchra.model.interfaces.Activity.ACTIVITY_TYPE;

	/**
	 * Storage table name of {@link #ACTIVITY_NODE} objects.
	 */
	public static final String KO_NAME_ACTIVITY = "GenericObject";

	/**
	 * Name of type <code>Company</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Company#COMPANY_TYPE}.
	 */
	@Deprecated
	public static final String COMPANY_NODE = com.top_logic.synchra.model.interfaces.Company.COMPANY_TYPE;

	/**
	 * Storage table name of {@link #COMPANY_NODE} objects.
	 */
	public static final String KO_NAME_COMPANY = "GenericObject";

	/**
	 * Name of type <code>Component</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Component#COMPONENT_TYPE}.
	 */
	@Deprecated
	public static final String COMPONENT_NODE = com.top_logic.synchra.model.interfaces.Component.COMPONENT_TYPE;

	/**
	 * Name of type <code>ConstructionGroup</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.ConstructionGroup#CONSTRUCTION_GROUP_TYPE}.
	 */
	@Deprecated
	public static final String CONSTRUCTION_GROUP_NODE = com.top_logic.synchra.model.interfaces.ConstructionGroup.CONSTRUCTION_GROUP_TYPE;

	/**
	 * Storage table name of {@link #CONSTRUCTION_GROUP_NODE} objects.
	 */
	public static final String KO_NAME_CONSTRUCTION_GROUP = "GenericObject";

	/**
	 * Name of type <code>SinglePart</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.SinglePart#SINGLE_PART_TYPE}.
	 */
	@Deprecated
	public static final String SINGLE_PART_NODE = com.top_logic.synchra.model.interfaces.SinglePart.SINGLE_PART_TYPE;

	/**
	 * Storage table name of {@link #SINGLE_PART_NODE} objects.
	 */
	public static final String KO_NAME_SINGLE_PART = "GenericObject";

	/**
	 * Name of type <code>ComponentNode</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.ComponentNode#COMPONENT_NODE_TYPE}.
	 */
	@Deprecated
	public static final String COMPONENT_NODE_NODE = com.top_logic.synchra.model.interfaces.ComponentNode.COMPONENT_NODE_TYPE;

	/**
	 * Storage table name of {@link #COMPONENT_NODE_NODE} objects.
	 */
	public static final String KO_NAME_COMPONENT_NODE = "GenericObject";

	/**
	 * Name of type <code>Connection</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Connection#CONNECTION_TYPE}.
	 */
	@Deprecated
	public static final String CONNECTION_NODE = com.top_logic.synchra.model.interfaces.Connection.CONNECTION_TYPE;

	/**
	 * Storage table name of {@link #CONNECTION_NODE} objects.
	 */
	public static final String KO_NAME_CONNECTION = "GenericObject";

	/**
	 * Name of type <code>Material</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Material#MATERIAL_TYPE}.
	 */
	@Deprecated
	public static final String MATERIAL_NODE = com.top_logic.synchra.model.interfaces.Material.MATERIAL_TYPE;

	/**
	 * Storage table name of {@link #MATERIAL_NODE} objects.
	 */
	public static final String KO_NAME_MATERIAL = "GenericObject";

	/**
	 * Name of type <code>PartCatalog</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.PartCatalog#PART_CATALOG_TYPE}.
	 */
	@Deprecated
	public static final String PART_CATALOG_NODE = com.top_logic.synchra.model.interfaces.PartCatalog.PART_CATALOG_TYPE;

	/**
	 * Storage table name of {@link #PART_CATALOG_NODE} objects.
	 */
	public static final String KO_NAME_PART_CATALOG = "GenericObject";

	/**
	 * Name of type <code>PartsGroup</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.PartsGroup#PARTS_GROUP_TYPE}.
	 */
	@Deprecated
	public static final String PARTS_GROUP_NODE = com.top_logic.synchra.model.interfaces.PartsGroup.PARTS_GROUP_TYPE;

	/**
	 * Storage table name of {@link #PARTS_GROUP_NODE} objects.
	 */
	public static final String KO_NAME_PARTS_GROUP = "GenericObject";

	/**
	 * Name of type <code>PartsListEntry</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.PartsListEntry#PARTS_LIST_ENTRY_TYPE}.
	 */
	@Deprecated
	public static final String PARTS_LIST_ENTRY_NODE = com.top_logic.synchra.model.interfaces.PartsListEntry.PARTS_LIST_ENTRY_TYPE;

	/**
	 * Storage table name of {@link #PARTS_LIST_ENTRY_NODE} objects.
	 */
	public static final String KO_NAME_PARTS_LIST_ENTRY = "GenericObject";

	/**
	 * Name of type <code>Problem</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Problem#PROBLEM_TYPE}.
	 */
	@Deprecated
	public static final String PROBLEM_NODE = com.top_logic.synchra.model.interfaces.Problem.PROBLEM_TYPE;

	/**
	 * Storage table name of {@link #PROBLEM_NODE} objects.
	 */
	public static final String KO_NAME_PROBLEM = "GenericObject";

	/**
	 * Name of type <code>Product</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.Product#PRODUCT_TYPE}.
	 */
	@Deprecated
	public static final String PRODUCT_NODE = com.top_logic.synchra.model.interfaces.Product.PRODUCT_TYPE;

	/**
	 * Storage table name of {@link #PRODUCT_NODE} objects.
	 */
	public static final String KO_NAME_PRODUCT = "GenericObject";

	/**
	 * Name of type <code>ProductSelection</code> in structure {@link #SYN_STRUCTURE}.
	 * 
	 * @deprecated Use {@link com.top_logic.synchra.model.interfaces.ProductSelection#PRODUCT_SELECTION_TYPE}.
	 */
	@Deprecated
	public static final String PRODUCT_SELECTION_NODE = com.top_logic.synchra.model.interfaces.ProductSelection.PRODUCT_SELECTION_TYPE;

	/**
	 * Storage table name of {@link #PRODUCT_SELECTION_NODE} objects.
	 */
	public static final String KO_NAME_PRODUCT_SELECTION = "GenericObject";


	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Activity} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Activity createActivity(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.Activity) createObject(getActivityType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Activity} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Activity createActivity() {
		return createActivity(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Company} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Company createCompany(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.Company) createObject(getCompanyType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Company} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Company createCompany() {
		return createCompany(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup} type.
	 */
	public final com.top_logic.synchra.model.interfaces.ConstructionGroup createConstructionGroup(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.ConstructionGroup) createObject(getConstructionGroupType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.ConstructionGroup} type.
	 */
	public final com.top_logic.synchra.model.interfaces.ConstructionGroup createConstructionGroup() {
		return createConstructionGroup(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.SinglePart} type.
	 */
	public final com.top_logic.synchra.model.interfaces.SinglePart createSinglePart(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.SinglePart) createObject(getSinglePartType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.SinglePart} type.
	 */
	public final com.top_logic.synchra.model.interfaces.SinglePart createSinglePart() {
		return createSinglePart(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.ComponentNode} type.
	 */
	public final com.top_logic.synchra.model.interfaces.ComponentNode createComponentNode(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.ComponentNode) createObject(getComponentNodeType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.ComponentNode} type.
	 */
	public final com.top_logic.synchra.model.interfaces.ComponentNode createComponentNode() {
		return createComponentNode(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Connection} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Connection createConnection(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.Connection) createObject(getConnectionType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Connection} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Connection createConnection() {
		return createConnection(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Material} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Material createMaterial(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.Material) createObject(getMaterialType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Material} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Material createMaterial() {
		return createMaterial(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.PartCatalog} type.
	 */
	public final com.top_logic.synchra.model.interfaces.PartCatalog createPartCatalog(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.PartCatalog) createObject(getPartCatalogType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.PartCatalog} type.
	 */
	public final com.top_logic.synchra.model.interfaces.PartCatalog createPartCatalog() {
		return createPartCatalog(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.PartsGroup} type.
	 */
	public final com.top_logic.synchra.model.interfaces.PartsGroup createPartsGroup(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.PartsGroup) createObject(getPartsGroupType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.PartsGroup} type.
	 */
	public final com.top_logic.synchra.model.interfaces.PartsGroup createPartsGroup() {
		return createPartsGroup(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.PartsListEntry} type.
	 */
	public final com.top_logic.synchra.model.interfaces.PartsListEntry createPartsListEntry(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.PartsListEntry) createObject(getPartsListEntryType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.PartsListEntry} type.
	 */
	public final com.top_logic.synchra.model.interfaces.PartsListEntry createPartsListEntry() {
		return createPartsListEntry(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Problem} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Problem createProblem(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.Problem) createObject(getProblemType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Problem} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Problem createProblem() {
		return createProblem(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Product} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Product createProduct(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.Product) createObject(getProductType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.Product} type.
	 */
	public final com.top_logic.synchra.model.interfaces.Product createProduct() {
		return createProduct(null);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.ProductSelection} type.
	 */
	public final com.top_logic.synchra.model.interfaces.ProductSelection createProductSelection(com.top_logic.model.TLObject context) {
		return (com.top_logic.synchra.model.interfaces.ProductSelection) createObject(getProductSelectionType(), context);
	}

	/**
	 * Create an instance of {@link com.top_logic.synchra.model.interfaces.ProductSelection} type.
	 */
	public final com.top_logic.synchra.model.interfaces.ProductSelection createProductSelection() {
		return createProductSelection(null);
	}

	/**
	 * The singleton instance of {@link ModelFactory}.
	 */
	public static ModelFactory getInstance() {
		return (ModelFactory) com.top_logic.element.model.DynamicModelService.getFactoryFor(SYN_STRUCTURE);
	}
}
