/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.risk.implementation;

/**
 * Basic interface for {@link #COLOR_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ColorBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Color</code>
	 */
	String COLOR_TYPE = "Color";

	/**
	 * Part <code>color</code> of <code>Color</code>
	 * 
	 * <p>
	 * Declared as <code>tl.util:Color</code> in configuration.
	 * </p>
	 */
	String COLOR_ATTR = "color";

	/**
	 * Part <code>name</code> of <code>Color</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.i18n:I18NString</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>rgb</code> of <code>Color</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String RGB_ATTR = "rgb";

	/**
	 * Getter for part {@link #COLOR_ATTR}.
	 */
	default java.awt.Color getColor() {
		return (java.awt.Color) tValueByName(COLOR_ATTR);
	}

	/**
	 * Setter for part {@link #COLOR_ATTR}.
	 */
	default void setColor(java.awt.Color newValue) {
		tUpdateByName(COLOR_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #RGB_ATTR}.
	 */
	default String getRgb() {
		return (String) tValueByName(RGB_ATTR);
	}

	/**
	 * Setter for part {@link #RGB_ATTR}.
	 */
	default void setRgb(String newValue) {
		tUpdateByName(RGB_ATTR, newValue);
	}

}
