/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.risk.implementation;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>risk:Probability</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class ProbabilityImpl extends com.top_logic.element.meta.kbbased.AttributedWrapper implements com.top_logic.synchra.risk.interfaces.Probability {

	/**
	 * Default constructor.
	 */
	public ProbabilityImpl(KnowledgeObject ko) {
		super(ko);
	}

}
