/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.synchra.risk.implementation;

/**
 * Basic interface for {@link #RISK_KIND_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface RiskKindBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>RiskKind</code>
	 */
	String RISK_KIND_TYPE = "RiskKind";

	/**
	 * Part <code>description</code> of <code>RiskKind</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.i18n:I18NHtml</code> in configuration.
	 * </p>
	 */
	String DESCRIPTION_ATTR = "description";

	/**
	 * Part <code>name</code> of <code>RiskKind</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.i18n:I18NString</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Getter for part {@link #DESCRIPTION_ATTR}.
	 */
	default com.top_logic.layout.wysiwyg.ui.i18n.I18NStructuredText getDescription() {
		return (com.top_logic.layout.wysiwyg.ui.i18n.I18NStructuredText) tValueByName(DESCRIPTION_ATTR);
	}

	/**
	 * Setter for part {@link #DESCRIPTION_ATTR}.
	 */
	default void setDescription(com.top_logic.layout.wysiwyg.ui.i18n.I18NStructuredText newValue) {
		tUpdateByName(DESCRIPTION_ATTR, newValue);
	}

}
